version: '3'

services: 
    lpb:
        build: 
            context: .
            args: 
                ITERATIONS: 100
                DB_SIZE: 100000
                EXPERIMENT_LABEL: Label
        ports: 
            - "80:80"